# Generated by Django 5.2.14 on 2026-08-29 09:45

import authentication.utils.upload_helpers
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Career College', help_text='Issuing organization printed on certificates.', max_length=200)),
                ('authorized_signatory_name', models.CharField(blank=True, default='', max_length=200)),
                ('authorized_signatory_designation', models.CharField(blank=True, default='', max_length=200)),
                ('authorized_signature', models.ImageField(blank=True, help_text='Transparent PNG preferred. Copied onto certificates at issuance.', null=True, upload_to=authentication.utils.upload_helpers.authorized_signature_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Upload a valid image. Allowed formats: JPG, JPEG, PNG, WEBP.'), core.validators.validate_signature_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('suspend', 'Suspend'), ('reactivate', 'Reactivate'), ('role_change', 'Role change'), ('certificate_revoke', 'Certificate revoked'), ('certificate_restore', 'Certificate restored'), ('platform_settings_update', 'Platform settings updated')], db_index=True, max_length=32),
        ),
    ]
