# Generated by Django 5.2.14 on 2026-09-01 06:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0003_platformsettings_alter_adminactionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Platform-wide payout commission percentage, snapshotted onto each Payout at generation time.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('suspend', 'Suspend'), ('reactivate', 'Reactivate'), ('role_change', 'Role change'), ('certificate_revoke', 'Certificate revoked'), ('certificate_restore', 'Certificate restored'), ('platform_settings_update', 'Platform settings updated'), ('payout_account_verify', 'Payout account verified'), ('payout_approve', 'Payout approved'), ('payout_reject', 'Payout rejected'), ('payout_mark_paid', 'Payout marked paid')], db_index=True, max_length=32),
        ),
    ]
