from analytics.all_views import (
    AdminAnalyticsSummaryView,
    AdminCertificateTrendView,
    AdminEnrollmentTrendView,
    AdminFunnelView,
    AdminRevenueTrendView,
    AdminTopCoursesView,
    AdminUserTrendView,
    InstitutionAnalyticsSummaryView,
    InstitutionCertificateTrendView,
    InstitutionEnrollmentTrendView,
    InstitutionExpertPerformanceDetailView,
    InstitutionExpertPerformanceView,
    InstitutionTopCoursesView,
    InstitutionWebinarTrendView,
)

__all__ = [
    'InstitutionAnalyticsSummaryView',
    'InstitutionCertificateTrendView',
    'InstitutionEnrollmentTrendView',
    'InstitutionExpertPerformanceDetailView',
    'InstitutionExpertPerformanceView',
    'InstitutionTopCoursesView',
    'InstitutionWebinarTrendView',
    'AdminAnalyticsSummaryView',
    'AdminCertificateTrendView',
    'AdminEnrollmentTrendView',
    'AdminFunnelView',
    'AdminRevenueTrendView',
    'AdminTopCoursesView',
    'AdminUserTrendView',
]
