# Generated by Django 5.2.14 on 2026-08-11 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('webinars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price snapshot at checkout time.', max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('tran_id', models.CharField(help_text='Our transaction id sent to the gateway (SSLCommerz max 30 chars).', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=12)),
                ('val_id', models.CharField(blank=True, default='', help_text='SSLCommerz validation id recorded after successful validation.', max_length=64)),
                ('gateway_payload', models.JSONField(blank=True, default=dict, help_text='Raw gateway session + validation responses, kept for audit.')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Course being purchased (mutually exclusive with webinar).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='courses.niduscourse')),
                ('schedule', models.ForeignKey(blank=True, help_text='Cohort schedule being purchased, if this is a cohort seat. Null = self-paced.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='courses.courseschedule')),
                ('user', models.ForeignKey(help_text='Learner who initiated the payment.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(blank=True, help_text='Webinar being purchased (mutually exclusive with course).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_order_user_status'), models.Index(fields=['course', 'status'], name='idx_order_course_status'), models.Index(fields=['webinar', 'status'], name='idx_order_webinar_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('webinar__isnull', True)), models.Q(('course__isnull', True), ('webinar__isnull', False)), _connector='OR'), name='chk_order_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('schedule__isnull', True), ('status', 'paid')), fields=('user', 'course'), name='uniq_paid_order_user_course_selfpaced'), models.UniqueConstraint(condition=models.Q(('schedule__isnull', False), ('status', 'paid')), fields=('user', 'schedule'), name='uniq_paid_order_user_schedule'), models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('user', 'webinar'), name='uniq_paid_order_user_webinar')],
            },
        ),
    ]
