# Generated by Django 5.2.14 on 2026-08-11 11:30

import courses.models
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'db_table': 'quiz_answers',
                'ordering': ['question_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('passing_score', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'courses_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('model_answer', models.TextField(blank=True, default='')),
                ('rubric', models.JSONField(blank=True, default=list, help_text='List of grading criteria, e.g. [{"type": "keyword", "value": "x", "points": 2, "feedback_on_match": "...", "feedback_on_miss": "..."}]. Sum of criterion.points must equal this question.points.')),
                ('points', models.PositiveIntegerField(default=0)),
                ('hint', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(db_index=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Question',
                'verbose_name_plural': 'Assignment Questions',
                'db_table': 'courses_assignment_question',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('grading', 'Grading'), ('passed', 'Passed'), ('failed', 'Failed'), ('grading_failed', 'Grading failed')], db_index=True, default='submitted', max_length=20)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField()),
                ('grading_error', models.TextField(blank=True, default='')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField()),
                ('rubric_snapshot', models.JSONField(blank=True, default=list)),
                ('criterion_results', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True, default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.assignmentquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'Assignment Submission Answer',
                'verbose_name_plural': 'Assignment Submission Answers',
                'db_table': 'assignment_submission_answers',
                'ordering': ['submission_id', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='CodingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20)),
                ('starter_code', models.TextField(blank=True, default='')),
                ('solution_code', models.TextField(blank=True, default='')),
                ('evaluation_script', models.TextField(blank=True, default='')),
                ('time_limit_ms', models.PositiveIntegerField(default=2000, help_text='Wall-clock budget for the WHOLE evaluation suite, in milliseconds.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coding_exercises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('grading', 'Grading'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('runtime_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.codingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coding Submission',
                'verbose_name_plural': 'Coding Submissions',
                'db_table': 'coding_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], db_index=True, max_length=10)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('runtime_ms', models.PositiveIntegerField(default=0)),
                ('exit_code', models.IntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='courses.codingsubmission')),
            ],
            options={
                'verbose_name': 'Coding Submission Test Result',
                'verbose_name_plural': 'Coding Submission Test Results',
                'db_table': 'coding_submission_test_results',
                'ordering': ['submission_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'course_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort_label', models.CharField(blank=True, help_text='Human-readable cohort name, e.g. "Fall 2026 Batch".', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone the dates are presented in.', max_length=64)),
                ('enrollment_opens_at', models.DateTimeField()),
                ('enrollment_closes_at', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Null = open-ended; the schedule stays ongoing until set.', null=True)),
                ('max_seats', models.PositiveIntegerField(blank=True, help_text='Null = unlimited seats.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Schedule',
                'verbose_name_plural': 'Course Schedules',
                'db_table': 'course_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('unlocks_at', models.DateTimeField(blank=True, help_text='Drip-release time for scheduled cohorts. Null = unlocked immediately.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'db_table': 'course_sections',
                'ordering': ['course_id', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='codingexercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercises', to='courses.coursesection'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.coursesection'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('admin_granted', 'Admin Granted')], db_index=True, default='free', max_length=15)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False when the learner unenrolls (soft revoke).')),
                ('progress_percent', models.PositiveIntegerField(default=0, help_text='Denormalized 0-100 completion percentage.', validators=[django.core.validators.MaxValueValidator(100)])),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when progress_percent first reached 100.', null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time the learner accessed course content.', null=True)),
                ('schedule', models.ForeignKey(blank=True, help_text='Cohort the learner enrolled through. Null = self-paced enrollment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.courseschedule')),
                ('user', models.ForeignKey(help_text='Learner enrolled in the course.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing UUID used in share/verify URLs.', unique=True)),
                ('learner_name', models.CharField(help_text='Snapshot of the learner full_name at time of issue.', max_length=200)),
                ('course_title', models.CharField(help_text='Snapshot of the course title at time of issue.', max_length=200)),
                ('issued_at', models.DateTimeField(help_text='Timestamp when the certificate was issued.')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'course_certificates',
            },
        ),
        migrations.CreateModel(
            name='LearnerActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(help_text='Local date of the activity, frozen at write time in settings.TIME_ZONE. Stored rather than derived so a later TIME_ZONE change cannot retroactively shift historical days.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Learner who was active.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Activity Day',
                'verbose_name_plural': 'Learner Activity Days',
                'db_table': 'learner_activity_days',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('lecture_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article')], db_index=True, default='video', max_length=20)),
                ('article_content', models.TextField(blank=True, default='')),
                ('stream_master_playlist', models.CharField(blank=True, default='', max_length=500)),
                ('stream_renditions', models.JSONField(blank=True, default=list)),
                ('transcoding_error', models.TextField(blank=True, default='')),
                ('is_preview', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.coursesection')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': 'lectures',
                'ordering': ['section_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NidusCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField()),
                ('learning_objectives', models.TextField(blank=True, default='', help_text='Outcome statements, one per line.')),
                ('prerequisites', models.TextField(blank=True, default='', help_text='Pre-course requirements, one per line.')),
                ('audiences', models.TextField(blank=True, default='', help_text='Intended audience segments, one per line.')),
                ('course_outline', models.TextField(blank=True, default='', help_text='Full topic/week-by-week outline. Required at submission for scheduled (cohort) courses in place of fully-authored sections; optional for self-paced courses.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=courses.models.course_thumbnail_upload_path)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Course list price in marketplace currency.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('language', models.CharField(db_index=True, default='English', max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Total course video duration in minutes.')),
                ('delivery_mode', models.CharField(choices=[('self_paced', 'Self-Paced'), ('scheduled', 'Scheduled (Cohort-Based)')], db_index=True, default='self_paced', help_text='Set at creation, immutable afterward. Scheduled courses do not require sections at submission (a written course_outline stands in) and require an attached CourseSchedule.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('institution_review', 'Institution Review'), ('under_review', 'Under Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Denormalized flag for fast published-course queries.')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory')),
                ('created_by', models.ForeignKey(help_text='User who initiated the course (instructor or partner institution).', on_delete=django.db.models.deletion.CASCADE, related_name='created_nidus_courses', to=settings.AUTH_USER_MODEL)),
                ('instructors', models.ManyToManyField(blank=True, help_text='One course can have one or many instructors.', related_name='instructed_nidus_courses', to=settings.AUTH_USER_MODEL)),
                ('partner_institution', models.ForeignKey(blank=True, help_text='Partner institution that owns this course. Set automatically when a partner institution creates the course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nidus_courses', to='authentication.partnerinstitutionprofile')),
            ],
            options={
                'verbose_name': 'Nidus Course',
                'verbose_name_plural': 'Nidus Courses',
                'db_table': 'nidus_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp_seconds', models.PositiveIntegerField(blank=True, help_text='Playback position the note refers to. Requires `lecture`.', null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='Flat list of lowercase tag strings.')),
                ('color', models.CharField(choices=[('default', 'Default'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('purple', 'Purple')], default='default', max_length=20)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(help_text='Learner who owns the note.', on_delete=django.db.models.deletion.CASCADE, related_name='learner_notes', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(blank=True, help_text='Lecture the note is anchored to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_notes', to='courses.lecture')),
                ('course', models.ForeignKey(blank=True, help_text='Course the note is filed under. Derived from `lecture` when omitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_notes', to='courses.niduscourse')),
            ],
            options={
                'verbose_name': 'Learner Note',
                'verbose_name_plural': 'Learner Notes',
                'db_table': 'learner_notes',
                'ordering': ['-is_pinned', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='Course the learner is enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.niduscourse'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.niduscourse'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.niduscourse'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headline', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courses.enrollment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.niduscourse')),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'db_table': 'course_reviews',
            },
        ),
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.niduscourse')),
            ],
            options={
                'verbose_name': 'Course Question',
                'verbose_name_plural': 'Course Questions',
                'db_table': 'course_questions',
                'ordering': ['-is_pinned', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_instructor_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_instructor_invites', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_invites', to='courses.niduscourse')),
            ],
            options={
                'verbose_name': 'Course Instructor Invite',
                'verbose_name_plural': 'Course Instructor Invites',
                'db_table': 'course_instructor_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_instructor_reply', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_replies', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursequestion')),
            ],
            options={
                'verbose_name': 'Question Reply',
                'verbose_name_plural': 'Question Replies',
                'db_table': 'question_replies',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_lectures', models.ManyToManyField(blank=True, help_text='Lectures this quiz is intended to assess. All must belong to the same section.', related_name='related_quizzes', to='courses.lecture')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursesection')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'quiz_attempts',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_questions',
                'ordering': ['quiz_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizattempt')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='courses.quizanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='courses.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Attempt Answer',
                'verbose_name_plural': 'Quiz Attempt Answers',
                'db_table': 'quiz_attempt_answers',
                'ordering': ['attempt_id', 'question_id'],
            },
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizquestion'),
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='courses.coursereview')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Vote',
                'verbose_name_plural': 'Review Votes',
                'db_table': 'review_votes',
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('lecture', 'Lecture'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('coding', 'Coding Exercise')], db_index=True, help_text='Discriminator for the type of content object in this slot.', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the related content object.')),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('content_type', models.ForeignKey(help_text='Django ContentType pointing to the concrete content model.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.coursesection')),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Section Contents',
                'db_table': 'section_contents',
                'ordering': ['section_id', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='related_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.sectioncontent'),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(upload_to=courses.models.video_asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'], message='Upload a valid video file. Allowed formats: MP4, MOV, AVI, MKV, WEBM.')])),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('master_playlist', models.CharField(blank=True, default='', max_length=500)),
                ('renditions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploading', max_length=20)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'Video Asset',
                'verbose_name_plural': 'Video Assets',
                'db_table': 'video_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='courses.videoasset')),
            ],
            options={
                'verbose_name': 'Video Processing Job',
                'verbose_name_plural': 'Video Processing Jobs',
                'db_table': 'video_processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='courses.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch Progress',
                'verbose_name_plural': 'Watch Progress',
                'db_table': 'watch_progress',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course saved to the wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.niduscourse')),
                ('user', models.ForeignKey(help_text='Learner who saved the course.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'db_table': 'course_wishlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignmentquestion',
            index=models.Index(fields=['assignment', 'position'], name='idx_aquestion_assign_position'),
        ),
        migrations.AddConstraint(
            model_name='assignmentquestion',
            constraint=models.UniqueConstraint(fields=('assignment', 'position'), name='uniq_aquestion_assignment_position'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['user', 'assignment', '-submitted_at'], name='idx_asub_user_assign_date'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='idx_asub_assign_status'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='idx_asub_user_date'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'grading'])), fields=('user', 'assignment'), name='uniq_inflight_assignment_submission'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmissionanswer',
            index=models.Index(fields=['submission', 'question'], name='idx_asubans_sub_question'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='uniq_submission_question'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['user', 'exercise', '-submitted_at'], name='idx_csub_user_ex_date'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['status'], name='idx_csub_status'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='idx_csub_user_date'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['submitted_at'], name='idx_csub_submitted_at'),
        ),
        migrations.AddIndex(
            model_name='codingsubmissiontestresult',
            index=models.Index(fields=['submission', 'position'], name='idx_csubres_sub_pos'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['is_active', 'name'], name='idx_ccat_active_name'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['section', '-created_at'], name='idx_assignment_section_date'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_uid'], name='idx_cert_uid'),
        ),
        migrations.AddIndex(
            model_name='learneractivityday',
            index=models.Index(fields=['user', '-activity_date'], name='idx_activity_user_date'),
        ),
        migrations.AddConstraint(
            model_name='learneractivityday',
            constraint=models.UniqueConstraint(fields=('user', 'activity_date'), name='uq_activity_day_user_date'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['lecture_type', 'section'], name='idx_lecture_type_section'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lecture_type', 'video'), ('article_content', '')), models.Q(('lecture_type', 'article'), ('article_content__gt', '')), _connector='OR'), name='chk_lecture_payload_by_type'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['status', '-created_at'], name='idx_ncourse_status_date'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['is_published', '-published_at'], name='idx_ncourse_pub_date'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['language', 'level'], name='idx_ncourse_lang_level'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['created_by', 'status'], name='idx_ncourse_creator_status'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['partner_institution', 'status'], name='idx_ncourse_inst_status'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['is_published', 'price'], name='idx_ncourse_pub_price'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['is_published', 'duration_minutes'], name='idx_ncourse_pub_duration'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['is_published', 'avg_rating'], name='idx_ncourse_pub_rating'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=models.Index(fields=['is_published', 'review_count'], name='idx_ncourse_pub_reviews'),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='idx_ncourse_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='niduscourse',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='idx_ncourse_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='learnernote',
            index=models.Index(fields=['user', '-is_pinned', '-updated_at'], name='idx_note_user_pin_upd'),
        ),
        migrations.AddIndex(
            model_name='learnernote',
            index=models.Index(fields=['user', 'course', '-updated_at'], name='idx_note_user_course_upd'),
        ),
        migrations.AddIndex(
            model_name='learnernote',
            index=models.Index(fields=['user', 'lecture'], name='idx_note_user_lecture'),
        ),
        migrations.AddIndex(
            model_name='learnernote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='idx_note_tags_gin'),
        ),
        migrations.AddConstraint(
            model_name='learnernote',
            constraint=models.CheckConstraint(condition=models.Q(('timestamp_seconds__isnull', True), ('lecture__isnull', False), _connector='OR'), name='chk_note_timestamp_requires_lecture'),
        ),
        migrations.AddConstraint(
            model_name='learnernote',
            constraint=models.CheckConstraint(condition=models.Q(('body__gt', '')), name='chk_note_body_not_empty'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'is_active', '-last_accessed_at'], name='idx_enroll_user_active_last'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_active'], name='idx_enroll_course_active'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_type'], name='idx_enroll_type'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', '-created_at'], name='idx_enroll_user_created'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', True)), fields=('user', 'course'), name='uniq_enrollment_user_course_selfpaced'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('user', 'schedule'), name='uniq_enrollment_user_schedule'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__lte', 100)), name='chk_enrollment_progress_percent_lte_100'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['course', 'position'], name='idx_csection_course_position'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='uniq_csection_course_position'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['course', 'status'], name='idx_cschedule_course_status'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-created_at'], name='idx_review_course_date'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-helpful_count'], name='idx_review_course_helpful'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', 'rating'], name='idx_review_course_rating'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['is_published', 'course'], name='idx_review_pub_course'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uq_review_user_course'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_review_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.CheckConstraint(condition=models.Q(('helpful_count__gte', 0)), name='chk_review_helpful_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.CheckConstraint(condition=models.Q(('not_helpful_count__gte', 0)), name='chk_review_not_helpful_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='courseinstructorinvite',
            index=models.Index(fields=['course', 'status'], name='idx_invite_course_status'),
        ),
        migrations.AddIndex(
            model_name='courseinstructorinvite',
            index=models.Index(fields=['invited_user', 'status'], name='idx_invite_user_status'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructorinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('course', 'invited_user'), name='unique_pending_invite_per_course'),
        ),
        migrations.AddIndex(
            model_name='questionreply',
            index=models.Index(fields=['question', 'is_deleted', 'created_at'], name='idx_reply_question_date'),
        ),
        migrations.AddConstraint(
            model_name='questionreply',
            constraint=models.CheckConstraint(condition=models.Q(('upvote_count__gte', 0)), name='chk_reply_upvote_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['section', '-created_at'], name='idx_quiz_section_date'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-submitted_at'], name='idx_qattempt_user_quiz_date'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-submitted_at'], name='idx_qattempt_quiz_date'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-submitted_at'], name='idx_qattempt_user_date'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'position'], name='idx_qquestion_quiz_position'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'position'), name='uniq_quizquestion_quiz_position'),
        ),
        migrations.AddIndex(
            model_name='quizattemptanswer',
            index=models.Index(fields=['attempt', 'question'], name='idx_qaanswer_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_answer_per_question'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['question', 'is_correct'], name='idx_qanswer_question_correct'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='uniq_correct_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(fields=('review', 'voter'), name='uq_vote_review_voter'),
        ),
        migrations.AddIndex(
            model_name='sectioncontent',
            index=models.Index(fields=['section', 'position'], name='idx_scontent_section_pos'),
        ),
        migrations.AddIndex(
            model_name='sectioncontent',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_scontent_ct_object'),
        ),
        migrations.AddIndex(
            model_name='sectioncontent',
            index=models.Index(fields=['item_type', 'section'], name='idx_scontent_itemtype_section'),
        ),
        migrations.AddConstraint(
            model_name='sectioncontent',
            constraint=models.UniqueConstraint(fields=('section', 'position'), name='uniq_scontent_section_position'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['course', 'is_deleted', '-created_at'], name='idx_question_course_date'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['course', 'is_deleted', '-upvote_count'], name='idx_question_course_upvotes'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['related_content'], name='idx_question_related_content'),
        ),
        migrations.AddConstraint(
            model_name='coursequestion',
            constraint=models.CheckConstraint(condition=models.Q(('reply_count__gte', 0)), name='chk_question_reply_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coursequestion',
            constraint=models.CheckConstraint(condition=models.Q(('upvote_count__gte', 0)), name='chk_question_upvote_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['lecture', 'is_active'], name='idx_vasset_lecture_active'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['status', '-created_at'], name='idx_vasset_status_date'),
        ),
        migrations.AddConstraint(
            model_name='videoasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('lecture',), name='uniq_active_videoasset_per_lecture'),
        ),
        migrations.AddIndex(
            model_name='videoprocessingjob',
            index=models.Index(fields=['video_asset', '-created_at'], name='idx_vjob_asset_date'),
        ),
        migrations.AddIndex(
            model_name='videoprocessingjob',
            index=models.Index(fields=['status', '-created_at'], name='idx_vjob_status_date'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['user', '-last_watched_at'], name='idx_wprogress_user_last'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['lecture', 'is_completed'], name='idx_wprogress_lecture_done'),
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lecture'), name='uniq_watch_progress_user_lecture'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', '-created_at'], name='idx_wishlist_user_date'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['course'], name='idx_wishlist_course'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uq_wishlist_user_course'),
        ),
    ]
