# Generated by Django 5.2.14 on 2026-08-24 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('career_goal', models.CharField(blank=True, default='', help_text='Hero heading shown on the path page. Falls back to title when blank.', max_length=200)),
                ('skill_tags', models.JSONField(blank=True, default=list, help_text='Flat list of display-only skill strings, e.g. ["Python", "MLOps"].')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Path Enrollment',
                'verbose_name_plural': 'Learning Path Enrollments',
                'db_table': 'learning_path_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', help_text='Stage label override, e.g. "Programming Foundations". Falls back to the course title when blank.', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_path_milestones', to='courses.niduscourse')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='courses.learningpath')),
            ],
            options={
                'verbose_name': 'Learning Path Milestone',
                'verbose_name_plural': 'Learning Path Milestones',
                'db_table': 'learning_path_milestones',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['status', '-created_at'], name='idx_lpath_status_created'),
        ),
        migrations.AddIndex(
            model_name='learningpathenrollment',
            index=models.Index(fields=['user', '-created_at'], name='idx_lpath_enroll_user_date'),
        ),
        migrations.AddConstraint(
            model_name='learningpathenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'path'), name='uq_lpath_enrollment_user_path'),
        ),
        migrations.AddIndex(
            model_name='learningpathmilestone',
            index=models.Index(fields=['path', 'position'], name='idx_lpath_milestone_order'),
        ),
        migrations.AddConstraint(
            model_name='learningpathmilestone',
            constraint=models.UniqueConstraint(fields=('path', 'position'), name='uq_lpath_milestone_position'),
        ),
        migrations.AddConstraint(
            model_name='learningpathmilestone',
            constraint=models.UniqueConstraint(fields=('path', 'course'), name='uq_lpath_milestone_course'),
        ),
    ]
