# Generated by Django 5.2.14 on 2026-08-30 06:58

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_learningpath_learningpathenrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niduscourse',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=courses.models.course_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='video_file',
            field=models.FileField(max_length=500, upload_to=courses.models.video_asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'], message='Upload a valid video file. Allowed formats: MP4, MOV, AVI, MKV, WEBM.')]),
        ),
    ]
