# Generated by Django 5.2.14 on 2026-08-29 09:45

import authentication.utils.upload_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_learningpath_learningpathenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='authorized_signatory_designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='authorized_signature',
            field=models.ImageField(blank=True, help_text='Frozen copy of the authorized signatory signature image.', null=True, upload_to=authentication.utils.upload_helpers.certificate_signature_path),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(db_index=True, help_text='Human-readable credential ID, e.g. CC-2026-NEXT-000123. Permanent — never regenerated after issuance.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date the learner completed the course.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_duration',
            field=models.CharField(blank=True, default='', help_text='Human-readable duration at issue time, e.g. "12 Weeks". Blank for self-paced courses with no cohort schedule.', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instructor_designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instructor_signature',
            field=models.ImageField(blank=True, help_text='Frozen copy of the instructor signature image.', null=True, upload_to=authentication.utils.upload_helpers.certificate_signature_path),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_name',
            field=models.CharField(blank=True, default='', help_text='Issuing organization at time of issue.', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='learning_hours',
            field=models.PositiveIntegerField(default=0, help_text='Snapshot of NidusCourse.learning_hours.'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], db_index=True, default='valid', max_length=20),
        ),
        migrations.AddField(
            model_name='niduscourse',
            name='learning_hours',
            field=models.PositiveIntegerField(default=0, help_text='Instructor-declared total learning hours, shown on the certificate. Distinct from duration_minutes, which is raw video runtime.'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='idx_cert_public_id'),
        ),
    ]
