# Generated by Django 5.2.14 on 2026-08-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_widen_media_path_fields'),
        ('courses', '0004_backfill_certificate_id'),
    ]

    operations = [
    ]
