# Generated by Django 5.2.14 on 2026-08-11 11:30

import authentication.utils.upload_helpers
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Required by the GinIndex(opclasses=['gin_trgm_ops']) declarations below
        # and by the trigram indexes in courses/0001_initial.
        TrigramExtension(),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Required for all users', max_length=255)),
                ('name_slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('partner_institution', 'Partner Institution'), ('admin', 'Admin')], db_index=True, default='learner', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False, help_text="Indicates if the user's email has been verified")),
                ('is_active', models.BooleanField(default=True, help_text='User account is active (NOT restricted by admin)')),
                ('is_restricted_by_admin', models.BooleanField(default=False, help_text='Account restricted by admin - user CANNOT reactivate themselves')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified account. Auto-set True for learners on registration; instructors and partner institutions require admin verification.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the user has deleted their account (soft delete)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the user deleted their account', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for account deletion', null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_purpose', models.CharField(blank=True, choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=20, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('password_reset_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('password_reset_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='authentication_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='authentication_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'education',
                'ordering': ['-is_current', '-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=authentication.utils.upload_helpers.learner_photo_path)),
                ('headline', models.CharField(blank=True, default='', help_text='Short tagline shown under the name, e.g. "Data Analyst at Google"', max_length=255)),
                ('bio', models.TextField(blank=True, default='', help_text='About / bio section')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('student', 'Student / No experience'), ('entry', 'Entry level (0–2 years)'), ('mid', 'Mid level (3–5 years)'), ('senior', 'Senior level (6–10 years)'), ('expert', 'Expert (10+ years)')], default='', max_length=10)),
                ('learning_goal', models.CharField(blank=True, default='', help_text='Primary learning objective, e.g. "Switch to a career in data science"', max_length=255)),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of topic interests, e.g. ["Python", "Machine Learning"]')),
                ('preferred_language', models.CharField(blank=True, default='English', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('is_profile_public', models.BooleanField(default=True, help_text='Whether the profile is visible to other learners')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Profile',
                'verbose_name_plural': 'Learner Profiles',
                'db_table': 'learner_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerInstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=authentication.utils.upload_helpers.institution_logo_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=authentication.utils.upload_helpers.institution_cover_path)),
                ('institution_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('tagline', models.CharField(blank=True, default='', help_text='Short institution tagline', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('institution_type', models.CharField(blank=True, choices=[('university', 'University'), ('college', 'College'), ('training_center', 'Training Center'), ('corporate', 'Corporate Training'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], default='', max_length=20)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('website_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-verified partner institution')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_institution_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Institution Profile',
                'verbose_name_plural': 'Partner Institution Profiles',
                'db_table': 'partner_institution_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=authentication.utils.upload_helpers.instructor_photo_path)),
                ('headline', models.CharField(blank=True, default='', help_text='Professional tagline, e.g. "Senior ML Engineer at Meta"', max_length=255)),
                ('bio', models.TextField(blank=True, default='', help_text='Instructor biography')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('specialization', models.JSONField(blank=True, default=list, help_text='Areas of expertise, e.g. ["Deep Learning", "NLP"]')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('current_title', models.CharField(blank=True, default='', help_text='Current job title', max_length=255)),
                ('current_organization', models.CharField(blank=True, default='', help_text='Current employer or affiliation', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-verified instructor')),
                ('is_accepting_students', models.BooleanField(default=True)),
                ('onboarding_source', models.CharField(choices=[('self', 'Self-Registered'), ('institution', 'Onboarded by Institution')], default='self', max_length=15)),
                ('affiliation_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('removed', 'Removed')], default='', help_text='Status of the institution affiliation', max_length=10)),
                ('affiliated_at', models.DateTimeField(blank=True, help_text='When the instructor joined the institution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department within the affiliated institution (institution-defined).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='authentication.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
                ('affiliated_institution', models.ForeignKey(blank=True, help_text='Partner institution this instructor belongs to (null if independent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='authentication.partnerinstitutionprofile')),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profiles',
                'db_table': 'instructor_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.partnerinstitutionprofile'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': 'work_experience',
                'ordering': ['-is_current', '-end_date', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_deleted', 'is_active'], name='idx_user_email_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='idx_user_type_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='idx_user_soft_delete'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'otp_purpose'], name='idx_user_email_otp'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified', 'user_type'], name='idx_user_verified_type'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_restricted_by_admin', 'is_active'], name='idx_user_restricted'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='idx_user_email_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='idx_user_fullname_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['user', '-start_date'], name='idx_edu_user_start'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['degree', 'institution'], name='idx_edu_degree_inst'),
        ),
        migrations.AddIndex(
            model_name='learnerprofile',
            index=models.Index(fields=['is_profile_public', 'country'], name='idx_learner_public_country'),
        ),
        migrations.AddIndex(
            model_name='learnerprofile',
            index=models.Index(fields=['experience_level'], name='idx_learner_exp_level'),
        ),
        migrations.AddIndex(
            model_name='partnerinstitutionprofile',
            index=models.Index(fields=['is_verified', 'is_active'], name='idx_partner_verified_active'),
        ),
        migrations.AddIndex(
            model_name='partnerinstitutionprofile',
            index=models.Index(fields=['institution_type', 'country'], name='idx_partner_type_country'),
        ),
        migrations.AddIndex(
            model_name='partnerinstitutionprofile',
            index=models.Index(fields=['institution_name'], name='idx_partner_name'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['is_verified', 'is_accepting_students'], name='idx_instr_verified_accept'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['affiliated_institution', 'affiliation_status'], name='idx_instr_affiliation'),
        ),
        migrations.AddIndex(
            model_name='instructorprofile',
            index=models.Index(fields=['country', 'city'], name='idx_instr_location'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('institution'), name='uniq_department_name_per_institution'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['user', '-start_date'], name='idx_work_user_start'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['company'], name='idx_work_company'),
        ),
    ]
