# Generated by Django 5.2.14 on 2026-08-29 09:45

import authentication.utils.upload_helpers
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Transparent PNG preferred. Copied onto certificates at issuance.', null=True, upload_to=authentication.utils.upload_helpers.instructor_signature_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Upload a valid image. Allowed formats: JPG, JPEG, PNG, WEBP.'), core.validators.validate_signature_size]),
        ),
        migrations.AddField(
            model_name='partnerinstitutionprofile',
            name='authorized_signatory_designation',
            field=models.CharField(blank=True, default='', help_text='Their designation, e.g. "Academic Director".', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerinstitutionprofile',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, default='', help_text='Person who authorizes certificates, e.g. "John Doe".', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerinstitutionprofile',
            name='authorized_signature',
            field=models.ImageField(blank=True, help_text='Transparent PNG preferred. Copied onto certificates at issuance.', null=True, upload_to=authentication.utils.upload_helpers.institution_signature_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Upload a valid image. Allowed formats: JPG, JPEG, PNG, WEBP.'), core.validators.validate_signature_size]),
        ),
    ]
