# Generated by Django 5.2.14 on 2026-09-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_instructorprofile_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinstitutionprofile',
            name='authorized_signatory_name',
            field=models.CharField(blank=True, default='', help_text='Person who authorizes certificates, e.g. "Imran Khan".', max_length=200),
        ),
    ]
