# Generated by Django 5.2.14 on 2026-09-01 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_partnerinstitutionprofile_authorized_signatory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking')], max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_routing_number', models.CharField(blank=True, default='', max_length=50)),
                ('mobile_banking_provider', models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], default='', max_length=20)),
                ('mobile_banking_number', models.CharField(blank=True, default='', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authentication.partnerinstitutionprofile')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Account',
                'verbose_name_plural': 'Payout Accounts',
                'db_table': 'payout_accounts',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('included_order_ids', models.JSONField(blank=True, default=list)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('payout_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payouts.payoutaccount')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payoutaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('institution__isnull', True), ('instructor__isnull', False)), models.Q(('institution__isnull', False), ('instructor__isnull', True)), _connector='OR'), name='chk_payoutaccount_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['payout_account', 'status'], name='payouts_payout__9fe973_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', '-requested_at'], name='payouts_status_2108a0_idx'),
        ),
    ]
