from id_verification.all_views import (
    VerificationCreateView,
    VerificationUpdateView,
    VerificationSubmitView,
    VerificationListView,
    VerificationDetailView,
    AdminVerificationListView,
    AdminVerificationDetailView,
    AdminVerificationReviewView,
    InstitutionVerificationCreateView,
    InstitutionVerificationUpdateView,
    InstitutionVerificationSubmitView,
    InstitutionVerificationListView,
    InstitutionVerificationDetailView,
    AdminInstitutionVerificationListView,
    AdminInstitutionVerificationDetailView,
    AdminInstitutionVerificationReviewView,
)
