# Generated by Django 5.2.14 on 2026-08-11 11:30

import core.validators
import django.core.validators
import django.db.models.deletion
import id_verification.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('residence_permit', 'Residence Permit')], default='', help_text='Type of identity document submitted', max_length=20)),
                ('document_number', models.CharField(blank=True, default='', help_text='ID/passport/licence number', max_length=100)),
                ('issuing_country', models.CharField(blank=True, default='', help_text='Country that issued the document', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date (if applicable)', null=True)),
                ('document_front', models.ImageField(blank=True, help_text='Front side of the identity document', upload_to=id_verification.utils.id_document_front_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Upload a valid image. Allowed formats: JPG, JPEG, PNG, WEBP.')])),
                ('document_back', models.ImageField(blank=True, help_text='Back side of the identity document (if applicable)', null=True, upload_to=id_verification.utils.id_document_back_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Upload a valid image. Allowed formats: JPG, JPEG, PNG, WEBP.')])),
                ('selfie', models.ImageField(blank=True, help_text='Selfie holding the identity document', upload_to=id_verification.utils.selfie_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Upload a valid image. Allowed formats: JPG, JPEG, PNG, WEBP.')])),
                ('resume', models.FileField(blank=True, help_text='Resume / CV document (PDF only)', null=True, upload_to=id_verification.utils.resume_path, validators=[core.validators.validate_pdf_file])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_required', 'Action Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason for rejection (required when rejecting)')),
                ('action_required_reason', models.TextField(blank=True, default='', help_text='What the instructor needs to fix (set by admin)')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes visible only to admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the instructor submitted (or resubmitted) the request', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Instructor who submitted the verification request', on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
                'db_table': 'instructor_identity_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_idv_user_status'), models.Index(fields=['status', '-created_at'], name='idx_idv_status_date'), models.Index(fields=['reviewed_by'], name='idx_idv_reviewer')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, default='', help_text='Official registration / accreditation number', max_length=100)),
                ('issuing_authority', models.CharField(blank=True, default='', help_text='Authority that issued the accreditation (e.g. Ministry of Education)', max_length=255)),
                ('official_email', models.EmailField(blank=True, default='', help_text='Official institutional contact email used for verification', max_length=254)),
                ('accreditation_document', models.FileField(blank=True, help_text='Accreditation / registration certificate (PDF or image)', upload_to=id_verification.utils.institution_accreditation_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Upload a valid document. Allowed formats: PDF, JPG, JPEG, PNG, WEBP.')])),
                ('authorization_letter', models.FileField(blank=True, help_text='Letter authorizing the admin to act for the institution (optional)', null=True, upload_to=id_verification.utils.institution_authorization_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Upload a valid document. Allowed formats: PDF, JPG, JPEG, PNG, WEBP.')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_required', 'Action Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason for rejection (required when rejecting)')),
                ('action_required_reason', models.TextField(blank=True, default='', help_text='What the institution needs to fix (set by admin)')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes visible only to admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the institution submitted (or resubmitted) the request', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(help_text='Partner institution that submitted the verification request', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='authentication.partnerinstitutionprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_institution_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution Verification',
                'verbose_name_plural': 'Institution Verifications',
                'db_table': 'institution_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'status'], name='idx_instv_inst_status'), models.Index(fields=['status', '-created_at'], name='idx_instv_status_date'), models.Index(fields=['reviewed_by'], name='idx_instv_reviewer')],
            },
        ),
    ]
