# Generated by Django 5.2.14 on 2026-08-11 11:30

import django.core.validators
import django.db.models.deletion
import webinars.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_speakers', models.JSONField(blank=True, default=list, help_text='External presenters without a platform account: list of {full_name, title, bio}.')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=webinars.models.webinar_thumbnail_upload_path)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Webinar start time, stored in UTC.', null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Display time zone for the scheduled time, e.g. "Asia/Dhaka".', max_length=64)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of registrations. Null = unlimited.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('meeting_provider', models.CharField(choices=[('zoom', 'Zoom'), ('meet', 'Google Meet'), ('jitsi', 'Jitsi'), ('other', 'Other')], default='other', max_length=10)),
                ('meeting_url', models.URLField(blank=True, help_text='External meeting join link. Exposed only to registrants.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Denormalized flag for fast published-webinar queries.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='courses.coursecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('host_expert', models.ForeignKey(blank=True, help_text='Assigned platform-expert host. Set via the host endpoint (active affiliated expert).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_webinars', to=settings.AUTH_USER_MODEL)),
                ('institutional_speakers', models.ManyToManyField(blank=True, help_text='Active affiliated experts of the owning institution credited as speakers. Credit-only — no authoring rights.', related_name='speaking_webinars', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner_institution', models.ForeignKey(blank=True, help_text='Partner institution that owns this webinar. Set automatically at creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='authentication.partnerinstitutionprofile')),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'db_table': 'webinars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False when the learner cancels (soft revoke).')),
                ('attended', models.BooleanField(default=False, help_text='Set when the learner joins the live session (later phase).')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Learner registered for the webinar.', on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(help_text='Webinar the learner registered for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar Registration',
                'verbose_name_plural': 'Webinar Registrations',
                'db_table': 'webinar_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['status', '-created_at'], name='idx_webinar_status_date'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['is_published', 'scheduled_at'], name='idx_webinar_pub_sched'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['partner_institution', 'status'], name='idx_webinar_inst_status'),
        ),
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='idx_wreg_user_active'),
        ),
        migrations.AddIndex(
            model_name='webinarregistration',
            index=models.Index(fields=['webinar', 'is_active'], name='idx_wreg_webinar_active'),
        ),
        migrations.AddConstraint(
            model_name='webinarregistration',
            constraint=models.UniqueConstraint(fields=('user', 'webinar'), name='uniq_registration_user_webinar'),
        ),
    ]
