# Generated by Django 5.2.14 on 2026-08-11 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enrollment.created', 'Enrollment Created'), ('lecture.completed', 'Lecture Completed'), ('course.completed', 'Course Completed'), ('course.submitted_for_review', 'Course Submitted for Review'), ('course.approved', 'Course Approved'), ('course.rejected', 'Course Rejected'), ('course.archived', 'Course Archived'), ('course.marked_finished', 'Course Marked Finished'), ('course.sent_back', 'Course Sent Back'), ('course.schedule_needs_attention', 'Course Schedule Needs Attention'), ('video.transcoding_completed', 'Video Transcoding Completed'), ('video.transcoding_failed', 'Video Transcoding Failed'), ('invite.sent', 'Invite Sent'), ('invite.accepted', 'Invite Accepted'), ('invite.declined', 'Invite Declined'), ('review.received', 'Review Received'), ('learner.enrolled', 'Learner Enrolled'), ('verification.submitted', 'Verification Submitted'), ('verification.approved', 'Verification Approved'), ('verification.rejected', 'Verification Rejected'), ('verification.action_required', 'Verification Action Required'), ('institution_verification.submitted', 'Institution Verification Submitted'), ('institution_verification.approved', 'Institution Verification Approved'), ('institution_verification.rejected', 'Institution Verification Rejected'), ('institution_verification.action_required', 'Institution Verification Action Required'), ('expert.onboarded', 'Expert Onboarded'), ('message.received', 'Message Received'), ('webinar.published', 'Webinar Published'), ('webinar.registered', 'Webinar Registration Confirmed'), ('payment.successful', 'Payment Successful'), ('payment.failed', 'Payment Failed'), ('account.suspended', 'Account Suspended'), ('account.reactivated', 'Account Reactivated'), ('question.posted', 'Question Posted'), ('question.replied', 'Question Replied')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('deduplication_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('course_activity', 'Course Activity'), ('assessments', 'Assessments'), ('course_management', 'Course Management'), ('collaboration', 'Collaboration'), ('verification', 'Verification'), ('messaging', 'Messaging')], max_length=64)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
