from .course_serializers import *
from .content_serializers import *
from .assessment_serializers import *
from .enrollment_serializers import *
from .learner_serializers import *
from .certificate_serializers import *
from .review_serializers import *
from .schedule_serializers import *
from .discussion_serializers import *
from .wishlist_serializers import *
from .note_serializers import *
from .dashboard_serializers import *
from .learning_path_serializers import *
