from courses.all_views import (
    CourseAudienceDetailAPIView,
    CourseAudienceListCreateAPIView,
    CourseCreateAPIView,
    CourseDetailView,
    CourseLearningObjectiveDetailAPIView,
    CourseLearningObjectiveListCreateAPIView,
    CourseListAPIView,
    CoursePreRequisiteDetailAPIView,
    CoursePreRequisiteListCreateAPIView,
    CourseSectionCreateAPIView,
    CourseSectionDetailAPIView,
    CourseSectionListAPIView,
    LectureCreateAPIView,
    LectureDetailAPIView,
    LectureListAPIView,
)

__all__ = [
    'CourseListAPIView',
    'CourseCreateAPIView',
    'CourseDetailView',
    'CourseLearningObjectiveListCreateAPIView',
    'CourseLearningObjectiveDetailAPIView',
    'CoursePreRequisiteListCreateAPIView',
    'CoursePreRequisiteDetailAPIView',
    'CourseAudienceListCreateAPIView',
    'CourseAudienceDetailAPIView',
    'CourseSectionListAPIView',
    'CourseSectionCreateAPIView',
    'CourseSectionDetailAPIView',
    'LectureListAPIView',
    'LectureCreateAPIView',
    'LectureDetailAPIView',
]
